name = "pew-ingest"
main = "src/index.ts"
compatibility_date = "2026-03-01"
workers_dev = true

[[routes]]
pattern = "pew-ingest.worker.hexly.ai"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "pew-db"
database_id = "5c00ebbf-a0ed-49d9-a64f-5712c272e96f"
